In [25]:
import numpy as n

In [26]:
# ouestion 1
arr = n.random.randint(0,120,60)
arr14=arr.reshape(12,5)
print(arr14)
lst=[11]
lst1=[0,1,2,3,4]
j=10
for x in (lst):
    for y in lst1:
        arr14[x][y]=j
        j+=1
print("                                  ")
print(arr14)



[[ 60  19   4 113 100]
 [ 97  13  96  51 117]
 [ 82  28  20  65  23]
 [102  22 107   7 116]
 [ 64  72   0  22   1]
 [  2  67  71 118  92]
 [ 16 112  90  38  43]
 [ 37  50  55  49  44]
 [ 61  83 116  35  58]
 [ 93  56  58  32  60]
 [ 67  47  86  87  16]
 [ 25  76 117  72  83]]
                                  
[[ 60  19   4 113 100]
 [ 97  13  96  51 117]
 [ 82  28  20  65  23]
 [102  22 107   7 116]
 [ 64  72   0  22   1]
 [  2  67  71 118  92]
 [ 16 112  90  38  43]
 [ 37  50  55  49  44]
 [ 61  83 116  35  58]
 [ 93  56  58  32  60]
 [ 67  47  86  87  16]
 [ 10  11  12  13  14]]


In [27]:
#question 2
arr1 = n.random.randint(0,120,60)
arr3=arr1.reshape(12,5)
print (arr3)
i=0
for row in arr3:
    print("the max of the row ",i,"is:",max(row))
    print("the min of the row ",i,"is:",min(row))
    i+=1




    

[[ 24  52  27  56 102]
 [ 75  78  39 112 107]
 [ 96  26  83  16  57]
 [ 65 105  25  84  32]
 [ 62 119  56  40  82]
 [ 93  38   6  57   3]
 [112  50 114  13  64]
 [ 15  40  58  59 115]
 [ 67  14  14 104  11]
 [ 10  55  52  37  24]
 [ 67  34  51  89  27]
 [104  97 115  23  62]]
the max of the row  0 is: 102
the min of the row  0 is: 24
the max of the row  1 is: 112
the min of the row  1 is: 39
the max of the row  2 is: 96
the min of the row  2 is: 16
the max of the row  3 is: 105
the min of the row  3 is: 25
the max of the row  4 is: 119
the min of the row  4 is: 40
the max of the row  5 is: 93
the min of the row  5 is: 3
the max of the row  6 is: 114
the min of the row  6 is: 13
the max of the row  7 is: 115
the min of the row  7 is: 15
the max of the row  8 is: 104
the min of the row  8 is: 11
the max of the row  9 is: 55
the min of the row  9 is: 10
the max of the row  10 is: 89
the min of the row  10 is: 27
the max of the row  11 is: 115
the min of the row  11 is: 23
