In [2]:
#question1
import numpy as np 
def calculate(arr2):
    print("Average of the last row:",arr2[11].mean())
    print("Minimum of the last row:",arr2[11].min())
    print("Maximum of the last row:",arr2[11].max())
    count =0
    for i in arr2[11]:
        if(i%2==0):
            count+=1
    print("No of even in last row",count)

         


arr=np.random.randint(1,100,60)
arr1 =arr.reshape(12,5)
print("Array is:")
print(arr1)
calculate(arr1)

Array is:
[[54 69 11 72 14]
 [24 75 16 74 31]
 [86 90 59 18 51]
 [43 61 74 71 51]
 [67  1 69 69 61]
 [96 24 83 15 32]
 [93 49 91 36 84]
 [59 42 30 67  2]
 [80 74 53 58 77]
 [21 94 63 35 52]
 [66 97 44 23  4]
 [31 51 62 75 34]]
Average of the last row: 50.6
Minimum of the last row: 31
Maximum of the last row: 75
No of even in last row 2


In [4]:
#question 1 
arr=np.random.randint(1,100,60)
arr1 =arr.reshape(12,5)
print (arr1)
print()
print (arr1[:,-1::-1])

[[19 40 33 23 39]
 [20 20 22 57 23]
 [65 63 52 58 35]
 [44 19 58 95 88]
 [97 64 61 69 50]
 [ 2 98 29 22  6]
 [22 41 59 18 90]
 [46 58 33 57 72]
 [70 85  6 68 44]
 [44 34 20 49 48]
 [15  1 37 29 69]
 [64 94 91 88  1]]

[[39 23 33 40 19]
 [23 57 22 20 20]
 [35 58 52 63 65]
 [88 95 58 19 44]
 [50 69 61 64 97]
 [ 6 22 29 98  2]
 [90 18 59 41 22]
 [72 57 33 58 46]
 [44 68  6 85 70]
 [48 49 20 34 44]
 [69 29 37  1 15]
 [ 1 88 91 94 64]]
